_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.19.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 70
learning_rate:
    value: 0.001
prate:
    value: 0.2
weight_decay:
    value: 0.0005
