_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 64
data_path:
    value: /opt/img/effdl-cifar10/
epochs:
    value: 50
learning_rate:
    value: 0.001
save_path:
    value: ./group_8.pth
weight_decay:
    value: 0.0005
